GPUID: 0
WORKERS: 0
PRINT_FREQ: 10
SAVE_FREQ: 10
PIN_MEMORY: False
OUTPUT_DIR: 'reg_output'

CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True

DATASET:
  DATASET: CLPD
  ROOT: "/home/admin1/datasets/CLPD"
  CHAR_FILE: 'reg_lib/dataset/txt/LP_char.txt'
  JSON_FILE: {'train': '/home/admin1/datasets/CLPD/CLPD_train.txt',
              'val': '/home/admin1/datasets/CLPD/CLPD_test.txt'}
  SCALE_FACTOR: 0.25
  ROT_FACTOR: 30
  STD: 0.193
  MEAN: 0.588
  ALPHABETS: 'ABCDEFGHJKLMNPQRSTUVWXYZ0123456789皖沪津渝冀晋蒙辽吉黑苏浙京闽赣鲁豫鄂湘粤桂琼川贵云藏陕甘青宁新警藏O学I-'
#警藏o学i-
TRAIN:
  BATCH_SIZE_PER_GPU: 32
  SHUFFLE: True
  BEGIN_EPOCH: 0
  END_EPOCH: 30000
  RESUME:
    IS_RESUME: True
    FILE:  '/home/admin1/segmentation-net/reg_output/CLPD/crnn/2022-03-18-20-38/checkpoints/checkpoint_2943_acc_0.9100.pth'
  OPTIMIZER: 'adam'
  LR: 0.0001
  WD: 0.0
  LR_STEP: [60, 80]
  LR_FACTOR: 0.1
  MOMENTUM: 0.0
  NESTEROV: False
  RMSPROP_ALPHA:
  RMSPROP_CENTERED:

TEST:
  BATCH_SIZE_PER_GPU: 16
  SHUFFLE: True
  NUM_TEST: 1000
  NUM_TEST_DISP: 10

MODEL:
  NAME: 'crnn'
  USE_STN: False
  IMAGE_SIZE:
    OW: 280. # origial width: 280
    H: 32
    W: 160   # resized width: 160
  NUM_CLASSES: 0
  NUM_HIDDEN: 256

